name: dev_shawn分支自动打包

on:
  push:
    branches:
      - dev_shawn
  workflow_dispatch:

jobs:
  build-win-amd64:
    runs-on: windows-latest
    steps:
      - name: download source
        uses: actions/checkout@v3
        with:
          path: main

      - name: download updater
        uses: actions/checkout@v3
        with:
          repository: ArkMowers/updater
          path: updater

      - name: setup nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          install-only: true

      - name: Set up Python 3.8 amd64
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: pip
          architecture: x64

      - name: build frontend
        working-directory: ./main/ui
        shell: bash
        run: |
          npm ci
          npm run build
          cp -r dist ../

      - name: Install dependencies
        working-directory: ./main
        shell: cmd
        run: |
          python -m venv venv
          venv\Scripts\pip install opencv_contrib_python.whl
          venv\Scripts\pip install -r requirements.txt
          venv\Scripts\pip install -U pyinstaller xxhash backports.zoneinfo[tzdata]
      - name: Make package
        working-directory: ./main
        shell: cmd
        run: |
          set PYTHONHASHSEED=114514
          set SOURCE_DATE_EPOCH=1694076231
          venv\Scripts\pyinstaller .\webui_zip.spec

      - name: calculate hash
        working-directory: ./main/dist/mower
        shell: cmd
        run: |
          ..\..\venv\Scripts\python.exe ..\..\..\updater\publish.py

      - uses: actions/upload-artifact@v3
        with:
          name: mower
          path: main/dist/mower
