name: Windows Binary Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build-win-amd64:
    runs-on: windows-latest
    steps:
      - name: download frontend
        uses: actions/checkout@v3
        with:
          repository: ArkMowers/mower-ui
          path: mower-ui
          ref: ${{github.ref_name}}

      - name: download source
        uses: actions/checkout@v3
        with:
          path: main


      - name: setup nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          install-only: true

      - name: Set up Python 3.8 amd64
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64


      - name: build frontend
        working-directory: ./mower-ui
        shell: bash
        run: |
          npm install
          npm run build
          cp -r dist ../main/

      - name: Install dependencies
        working-directory: ./main
        shell: cmd
        run: |
          python -m venv venv
          venv\Scripts\pip install opencv_contrib_python.whl
          venv\Scripts\pip install -r requirements.txt
          venv\Scripts\pip install pyinstaller Flask flask-sock flask-cors pywebview
      - name: Patch Paddle
        working-directory: ./main
        shell: cmd
        run: |
          copy .\packaging\image.py .\venv\Lib\site-packages\paddle\dataset\image.py /y
          copy .\packaging\network.py .\venv\Lib\site-packages\paddleocr\ppocr\utils\network.py /y
          copy .\packaging\paddleocr.py .\venv\Lib\site-packages\paddleocr\paddleocr.py /y
      - name: Make package
        working-directory: ./main
        shell: cmd
        run: |
          venv\Scripts\pyinstaller .\webview.spec
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: main/dist/mower.exe
